import { Product } from "./types";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-001",
    seller_id: "seller-001",
    title: "VORTEX 500 GSM Heavyweight Modular Hoodie",
    slug: "vortex-heavyweight-modular-hoodie",
    description: "Architectural cut-and-sew heavyweight luxury hoodie in Pitch Black. Hand-distressed 500 GSM loopback French Terry with modular magnetic stash pockets and matte monochrome hardware.",
    product_type: "physical",
    base_price: 3499,
    platform_fee_percent: 15.0,
    thumbnail_url: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=1200&q=80",
    media_gallery: [
      "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=1200&q=80"
    ],
    status: "published",
    created_at: new Date(Date.now() - 3600000).toISOString(),
    updated_at: new Date().toISOString(),
    seller: {
      id: "seller-001",
      full_name: "KAIZEN STUDIOS",
      username: "kaizen",
      avatar_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
      is_verified: true,
      role: "seller",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    variants: [
      { id: "var-001-m", product_id: "prod-001", sku: "VTX-HD-BLK-M", title: "Pitch Black / M", price: 3499, inventory_count: 14, attributes: { size: "M", color: "Pitch Black" }, status: "active", created_at: new Date().toISOString() },
      { id: "var-001-l", product_id: "prod-001", sku: "VTX-HD-BLK-L", title: "Pitch Black / L", price: 3499, inventory_count: 8, attributes: { size: "L", color: "Pitch Black" }, status: "active", created_at: new Date().toISOString() },
      { id: "var-001-xl", product_id: "prod-001", sku: "VTX-HD-BLK-XL", title: "Pitch Black / XL", price: 3499, inventory_count: 3, attributes: { size: "XL", color: "Pitch Black" }, status: "active", created_at: new Date().toISOString() },
    ],
  },
  {
    id: "prod-002",
    seller_id: "seller-002",
    title: "NEO-BRUTALISM 3D UI & Shader Tokens Vault",
    slug: "neo-brutalism-3d-ui-tokens",
    description: "Comprehensive 3D motion shader library, WebGL tokens, React Three Fiber physics rigs, and 120+ pre-baked vector glyphs ready for immediate production deployment.",
    product_type: "digital_file",
    base_price: 1299,
    platform_fee_percent: 15.0,
    thumbnail_url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80",
    media_gallery: [
      "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80"
    ],
    status: "published",
    created_at: new Date(Date.now() - 7200000).toISOString(),
    updated_at: new Date().toISOString(),
    seller: {
      id: "seller-002",
      full_name: "GLYPH LABS",
      username: "glyphlabs",
      avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
      is_verified: true,
      role: "seller",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    digital_assets: [
      { id: "asset-002", product_id: "prod-002", r2_asset_key: "sellers/glyph/shader-tokens-v2.zip", file_name: "shader-tokens-v2.zip", file_size_bytes: 48920110, mime_type: "application/zip", version: 2, is_current: true, created_at: new Date().toISOString() }
    ],
  },
  {
    id: "prod-003",
    seller_id: "seller-003",
    title: "SYNAPSE OS • Notion Executive Operating System",
    slug: "synapse-os-notion-operating-system",
    description: "The autonomous operating system for creator enterprises, multi-brand studios, and angel syndicates. Pre-built with P&L trackers, deal flow pipelines, and client portals.",
    product_type: "digital_link",
    base_price: 899,
    platform_fee_percent: 15.0,
    thumbnail_url: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=1200&q=80",
    media_gallery: [
      "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=1200&q=80"
    ],
    status: "published",
    created_at: new Date(Date.now() - 14400000).toISOString(),
    updated_at: new Date().toISOString(),
    seller: {
      id: "seller-003",
      full_name: "AESTHETE SYSTEM",
      username: "aesthete",
      avatar_url: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80",
      is_verified: true,
      role: "seller",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    external_vault_links: [
      { id: "link-003", product_id: "prod-003", provider: "notion", destination_url: "https://notion.so/synapse-os-vault-master", access_instructions: "Duplicate template directly into your private Notion workspace.", status: "active", created_at: new Date().toISOString() }
    ],
  },
  {
    id: "prod-004",
    seller_id: "seller-001",
    title: "MONOLITH Acid-Wash Cyber Cargo Pants",
    slug: "monolith-acid-wash-cyber-cargo",
    description: "Tactical ripstop cargo pants featuring waterproof YKK zippers, detachable utility straps, custom gunmetal buckles, and reinforced knee articulation.",
    product_type: "physical",
    base_price: 4199,
    platform_fee_percent: 15.0,
    thumbnail_url: "https://images.unsplash.com/photo-1517445312882-bc9910d016b7?auto=format&fit=crop&w=1200&q=80",
    media_gallery: [
      "https://images.unsplash.com/photo-1517445312882-bc9910d016b7?auto=format&fit=crop&w=1200&q=80"
    ],
    status: "published",
    created_at: new Date(Date.now() - 28800000).toISOString(),
    updated_at: new Date().toISOString(),
    seller: {
      id: "seller-001",
      full_name: "KAIZEN STUDIOS",
      username: "kaizen",
      avatar_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
      is_verified: true,
      role: "seller",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    variants: [
      { id: "var-004-30", product_id: "prod-004", sku: "MNL-CRG-30", title: "Charcoal / 30", price: 4199, inventory_count: 5, attributes: { size: "30", color: "Charcoal" }, status: "active", created_at: new Date().toISOString() },
      { id: "var-004-32", product_id: "prod-004", sku: "MNL-CRG-32", title: "Charcoal / 32", price: 4199, inventory_count: 11, attributes: { size: "32", color: "Charcoal" }, status: "active", created_at: new Date().toISOString() },
      { id: "var-004-34", product_id: "prod-004", sku: "MNL-CRG-34", title: "Charcoal / 34", price: 4199, inventory_count: 6, attributes: { size: "34", color: "Charcoal" }, status: "active", created_at: new Date().toISOString() },
    ],
  },
  // ONLINE TECH & DEVELOPER SERVICES
  {
    id: "prod-005",
    seller_id: "seller-004",
    title: "Emergency Full-Stack Debug & Bug Fix Sprint (24h SLA)",
    slug: "emergency-fullstack-debug-sprint",
    description: "Instant emergency debugging for production web apps. We identify memory leaks, fix broken Next.js / React / Node.js API routes, resolve SSR hydration mismatches, and submit clean GitHub PRs within 24 hours.",
    product_type: "service",
    base_price: 4999,
    platform_fee_percent: 15.0,
    thumbnail_url: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1200&q=80",
    media_gallery: [
      "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1200&q=80"
    ],
    status: "published",
    created_at: new Date(Date.now() - 36000000).toISOString(),
    updated_at: new Date().toISOString(),
    seller: {
      id: "seller-004",
      full_name: "SYNTAX LABS",
      username: "syntaxlabs",
      avatar_url: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80",
      is_verified: true,
      role: "seller",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: "prod-006",
    seller_id: "seller-004",
    title: "Next.js 14 & Supabase Enterprise Architecture Sprint",
    slug: "nextjs-supabase-architecture-sprint",
    description: "Complete scalable backend and frontend scaffolding. Includes production Row-Level Security (RLS) policies, atomic inventory RPCs, server actions, payment route integration, and zero-trust Cloudflare R2 vault wiring in 3 days.",
    product_type: "service",
    base_price: 14999,
    platform_fee_percent: 15.0,
    thumbnail_url: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80",
    media_gallery: [
      "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80"
    ],
    status: "published",
    created_at: new Date(Date.now() - 43200000).toISOString(),
    updated_at: new Date().toISOString(),
    seller: {
      id: "seller-004",
      full_name: "SYNTAX LABS",
      username: "syntaxlabs",
      avatar_url: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80",
      is_verified: true,
      role: "seller",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: "prod-007",
    seller_id: "seller-002",
    title: "Smart Contract Security Audit & Hardening Report",
    slug: "smart-contract-security-audit",
    description: "Deep static and dynamic security audit for Solidity / EVM contracts. Reentrancy checks, overflow guards, gas optimization profiling, and formal cryptographic verification dossier.",
    product_type: "service",
    base_price: 19999,
    platform_fee_percent: 15.0,
    thumbnail_url: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?auto=format&fit=crop&w=1200&q=80",
    media_gallery: [
      "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?auto=format&fit=crop&w=1200&q=80"
    ],
    status: "published",
    created_at: new Date(Date.now() - 50400000).toISOString(),
    updated_at: new Date().toISOString(),
    seller: {
      id: "seller-002",
      full_name: "GLYPH LABS",
      username: "glyphlabs",
      avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
      is_verified: true,
      role: "seller",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: "prod-008",
    seller_id: "seller-003",
    title: "Cloudflare & AWS Cloud DevOps Pipeline Setup",
    slug: "cloudflare-aws-devops-pipeline",
    description: "Automated GitHub Actions CI/CD pipelines, Docker container orchestration, Cloudflare Workers & R2 zero-trust edge routing, SSL auto-renewals, and serverless observability monitoring.",
    product_type: "service",
    base_price: 9999,
    platform_fee_percent: 15.0,
    thumbnail_url: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80",
    media_gallery: [
      "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80"
    ],
    status: "published",
    created_at: new Date(Date.now() - 57600000).toISOString(),
    updated_at: new Date().toISOString(),
    seller: {
      id: "seller-003",
      full_name: "AESTHETE SYSTEM",
      username: "aesthete",
      avatar_url: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80",
      is_verified: true,
      role: "seller",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
  // ==========================================
  // DIGITAL ASSETS, SAAS, APPS & SOCIAL ACCOUNTS
  // ==========================================
  {
    id: "prod-009",
    seller_id: "seller-004",
    title: "VividAI • Automated Short-Form Video Generator SaaS",
    slug: "vividai-automated-video-generator-saas",
    description: "Revenue-generating B2B SaaS platform that converts long-form podcasts into viral TikTok/Reels with auto-captions and B-roll. Currently doing ₹48,500/mo verified MRR on Stripe with 82% gross margins. 100% turnkey asset including production codebase, domain, and Stripe customer base.",
    product_type: "saas",
    base_price: 450000,
    platform_fee_percent: 15.0,
    thumbnail_url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80",
    media_gallery: [
      "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80"
    ],
    asset_metrics: {
      mrr: 48500,
      arr: 582000,
      net_profit_monthly: 39000,
      tech_stack: ["Next.js 14", "FastAPI", "Replicate AI", "Stripe Billing", "Supabase", "TailwindCSS"],
      domain_name: "vividai.tools",
      monthly_visitors: 34200,
      is_monetized: true,
      transfer_items: [
        "Primary Domain (vividai.tools) EPP Auth Code Transfer",
        "Full GitHub Organization & Source Code Ownership",
        "Stripe Customer Base & Recurring Subscription Billing Transfer",
        "Cloudflare DNS & Vercel Production Environment Deployment Keys",
        "30 Days Post-Sale Developer Technical Support"
      ]
    },
    status: "published",
    created_at: new Date(Date.now() - 64800000).toISOString(),
    updated_at: new Date().toISOString(),
    seller: {
      id: "seller-004",
      full_name: "SYNTAX LABS",
      username: "syntaxlabs",
      avatar_url: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80",
      is_verified: true,
      role: "seller",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: "prod-010",
    seller_id: "seller-002",
    title: "PulseFit Pro • iOS & Android Flutter Fitness App",
    slug: "pulsefit-pro-flutter-fitness-app",
    description: "Published mobile fitness & micro-workout tracker app with 65,000+ organic downloads across Apple App Store and Google Play Store. Built with clean Flutter Clean Architecture, offline-first SQLite sync, and RevenueCat in-app subscriptions.",
    product_type: "app",
    base_price: 280000,
    platform_fee_percent: 15.0,
    thumbnail_url: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=1200&q=80",
    media_gallery: [
      "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?auto=format&fit=crop&w=1200&q=80"
    ],
    asset_metrics: {
      platform: "both",
      downloads_count: 65000,
      monthly_visitors: 14200,
      tech_stack: ["Flutter", "Dart", "Firebase", "RevenueCat", "App Store Connect", "Play Console"],
      is_monetized: true,
      transfer_items: [
        "Apple App Store Connect App Transfer (Zero downtime for existing users)",
        "Google Play Console App Transfer",
        "Complete Flutter / Dart Source Code Repository with documentation",
        "Figma UI Kit & Marketing Assets"
      ]
    },
    status: "published",
    created_at: new Date(Date.now() - 72000000).toISOString(),
    updated_at: new Date().toISOString(),
    seller: {
      id: "seller-002",
      full_name: "GLYPH LABS",
      username: "glyphlabs",
      avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
      is_verified: true,
      role: "seller",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: "prod-011",
    seller_id: "seller-004",
    title: "ApexEscrow • Multi-Vendor Split Commerce Core (Exclusive IP)",
    slug: "apexescrow-multi-vendor-commerce-core",
    description: "Battle-tested multi-tenant commerce and dual-entry escrow engine. Includes atomic inventory locks, 15% platform split calculator, Razorpay Route linked account dispatch, and Shiprocket automated tracking webhooks. Full commercial copyright assignment.",
    product_type: "source_code",
    base_price: 125000,
    platform_fee_percent: 15.0,
    thumbnail_url: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1200&q=80",
    media_gallery: [
      "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1200&q=80"
    ],
    asset_metrics: {
      license_type: "exclusive_ip",
      tech_stack: ["Next.js 14", "TypeScript", "PostgreSQL", "Supabase", "Razorpay Route", "Tailwind CSS"],
      github_repo_url: "github.com/syntaxlabs/apex-escrow-core",
      transfer_items: [
        "100% Exclusive Copyright & IP Assignment Contract",
        "Private GitHub Repository Ownership Transfer",
        "Database Migrations & PostgreSQL RPC Scripts",
        "Architecture Documentation & Setup Guide"
      ]
    },
    status: "published",
    created_at: new Date(Date.now() - 79200000).toISOString(),
    updated_at: new Date().toISOString(),
    seller: {
      id: "seller-004",
      full_name: "SYNTAX LABS",
      username: "syntaxlabs",
      avatar_url: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80",
      is_verified: true,
      role: "seller",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: "prod-012",
    seller_id: "seller-001",
    title: "@CodeVortexAI • 142k Subscribers YouTube Channel (Monetized)",
    slug: "codevortexai-142k-youtube-channel",
    description: "Verified active YouTube channel in the AI, Web Development & Next.js tutorial niche. 142,000+ real organic subscribers, 850k monthly video views, and active AdSense monetization generating ~₹45,000/month consistently. Zero strikes, clean standing.",
    product_type: "social_account",
    base_price: 390000,
    platform_fee_percent: 15.0,
    thumbnail_url: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?auto=format&fit=crop&w=1200&q=80",
    media_gallery: [
      "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1598550476439-6847785fcea6?auto=format&fit=crop&w=1200&q=80"
    ],
    asset_metrics: {
      platform: "youtube",
      handle: "@CodeVortexAI",
      followers_count: 142000,
      monthly_visitors: 850000,
      is_monetized: true,
      engagement_rate: "6.2%",
      transfer_items: [
        "Primary Google Brand Account Ownership Transfer (7-day standard handover security protocol)",
        "YouTube Studio Monetization & AdSense Account Re-link",
        "Associated Community Discord (12,000 members)",
        "Brand Sponsorship Outreach Template Pack"
      ]
    },
    status: "published",
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    seller: {
      id: "seller-001",
      full_name: "KAIZEN STUDIOS",
      username: "kaizen",
      avatar_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
      is_verified: true,
      role: "seller",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: "prod-013",
    seller_id: "seller-001",
    title: "@kaizen.streetwear • 88.5k Followers Instagram Brand Page",
    slug: "kaizen-streetwear-88k-instagram",
    description: "High-engagement aesthetic Instagram page in the Luxury Streetwear & Cyberpunk fashion niche. 88,500 organic followers, 4.8% average engagement rate, and verified story reach of 18k+ per drop. Perfect for launching direct-to-consumer apparel.",
    product_type: "social_account",
    base_price: 180000,
    platform_fee_percent: 15.0,
    thumbnail_url: "https://images.unsplash.com/photo-1611262588024-d12430b98920?auto=format&fit=crop&w=1200&q=80",
    media_gallery: [
      "https://images.unsplash.com/photo-1611262588024-d12430b98920?auto=format&fit=crop&w=1200&q=80"
    ],
    asset_metrics: {
      platform: "instagram",
      handle: "@kaizen.streetwear",
      followers_count: 88500,
      engagement_rate: "4.8%",
      is_monetized: false,
      transfer_items: [
        "Original Registration Email (OGE) Handover",
        "Instagram Account Credential Ownership Reset",
        "Supplier & Textile Mill Manufacturing Contact Rolodex",
        "High-Res Vector Brand Assets & Logo Files"
      ]
    },
    status: "published",
    created_at: new Date(Date.now() - 93600000).toISOString(),
    updated_at: new Date().toISOString(),
    seller: {
      id: "seller-001",
      full_name: "KAIZEN STUDIOS",
      username: "kaizen",
      avatar_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
      is_verified: true,
      role: "seller",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
];

export const MOCK_JOBS: import("./types").JobPosting[] = [
  {
    id: "job-001",
    company_name: "SYNTAX LABS",
    company_logo: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80",
    title: "Lead Full-Stack Next.js & Supabase Systems Architect",
    slug: "lead-fullstack-nextjs-systems-architect",
    role_category: "engineering",
    job_type: "full_time",
    location: "Remote (Global) / Bengaluru",
    salary_range: "₹28,00,000 - ₹45,00,000 / year + Equity",
    description: "Lead the core backend architecture for high-throughput sovereign commerce. You will build concurrency locking RPCs in PostgreSQL, optimize Cloudflare Workers and Edge R2 streaming, and build sub-50ms React server components.",
    requirements: [
      "5+ years building scalable React/Next.js App Router architectures.",
      "Expertise in Supabase PostgreSQL, custom plpgsql RPCs, and strict Row Level Security (RLS).",
      "Demonstrated experience with Redis atomic locking and high-concurrency payment integrations.",
      "Deep aesthetic standard for Monochrome Brutalism and micro-spring animations."
    ],
    benefits: [
      "100% Remote flexibility with flexible working hours.",
      "High-tier hardware stipend (M3 Max MacBook Pro / Studio Displays).",
      "Annual sovereign retreat and performance token bonus pool."
    ],
    contact_email: "careers@syntaxlabs.dev",
    status: "published",
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    applicant_count: 8,
  },
  {
    id: "job-002",
    company_name: "GLYPH LABS",
    company_logo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
    title: "Senior 3D Motion & WebGL Shader Technical Artist",
    slug: "senior-3d-motion-webgl-shader-artist",
    role_category: "design",
    job_type: "contract",
    location: "Remote (Global)",
    salary_range: "₹18,00,000 - ₹32,00,000 / year or $4,000/mo",
    description: "Design interactive WebGL, Three.js, and GLSL shaders for digital artifact vaults and interactive web drops. You will bridge procedural 3D modeling in Blender with 60fps browser rendering.",
    requirements: [
      "3+ years experience with Three.js, React Three Fiber (R3F), and custom GLSL fragment/vertex shaders.",
      "Proficiency in Blender procedural materials, baking lightmaps, and low-poly optimization for GLTF/GLB.",
      "Portfolio showcasing live interactive websites with high-performance WebGL canvas implementations."
    ],
    benefits: [
      "Full ownership of visual token pipelines.",
      "Direct profit share on curated 3D vault drop sales."
    ],
    contact_email: "studio@glyphlabs.xyz",
    status: "published",
    created_at: new Date(Date.now() - 172800000).toISOString(),
    updated_at: new Date().toISOString(),
    applicant_count: 5,
  },
  {
    id: "job-003",
    company_name: "KAIZEN STUDIOS",
    company_logo: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
    title: "Lead Cut-and-Sew Streetwear Fashion Designer & Pattern Maker",
    slug: "lead-streetwear-apparel-designer",
    role_category: "fashion",
    job_type: "full_time",
    location: "Mumbai / Bengaluru Studio",
    salary_range: "₹15,00,000 - ₹25,00,000 / year",
    description: "Architect heavyweight 500 GSM luxury garments from scratch. Responsibilities include tech pack drafting, sample fit development, sourcing bespoke loopback French Terry fabrics, and managing factory production runs.",
    requirements: [
      "Deep understanding of heavyweight knitwear (450-600 GSM), tactical hardware, and garment dyeing.",
      "Expertise in CLO 3D or Browzwear digital pattern drafting and tech-pack preparation.",
      "Experience interfacing with textile mills in Tirupur, Surat, and Ludhiana."
    ],
    benefits: [
      "Full access to sample development atelier and cutting room.",
      "Clothing allowance and VIP drops from every seasonal collection."
    ],
    contact_email: "design@kaizenstudios.in",
    status: "published",
    created_at: new Date(Date.now() - 259200000).toISOString(),
    updated_at: new Date().toISOString(),
    applicant_count: 12,
  },
  {
    id: "job-004",
    company_name: "AURAMINATOR PROTOCOL",
    company_logo: "/favicon.svg",
    title: "Growth Architect & Sovereign Creator Scout",
    slug: "growth-architect-creator-scout",
    role_category: "marketing",
    job_type: "full_time",
    location: "Remote / Hybrid Bengaluru",
    salary_range: "₹20,00,000 - ₹35,00,000 / year + Performance Incentives",
    description: "Identify and onboard top sovereign creators, elite digital 3D artists, and luxury streetwear brands onto the Auraminator marketplace engine. Drive viral drop mechanics and escrow volume.",
    requirements: [
      "Track record in creator economy growth, high-ticket digital product launches, or streetwear drops.",
      "Strong personal network among designers, developers, and fashion founders.",
      "Deep understanding of platform mechanics, split commerce, and buyer escrow guarantees."
    ],
    benefits: [
      "Direct commission bonus on onboarded creator GMV volume.",
      "Sovereign work environment with zero bureaucracy."
    ],
    contact_email: "partners@auraminator.in",
    status: "published",
    created_at: new Date(Date.now() - 345600000).toISOString(),
    updated_at: new Date().toISOString(),
    applicant_count: 19,
  },
];

export const MOCK_APPLICATIONS: import("./types").JobApplication[] = [
  {
    id: "app-101",
    job_id: "job-001",
    full_name: "Rohan Varma",
    email: "rohan.varma@devmail.com",
    phone: "+91 98765 43210",
    portfolio_url: "https://rohanvarma.codes",
    github_url: "https://github.com/rohanvarma",
    resume_url: "https://assets.auraminator.in/resumes/rohan-varma-senior-architect.pdf",
    cover_note: "I have 6 years of experience building high-concurrency commerce systems with Next.js 14, Supabase, and Redis locks. I recently scaled an escrow checkout engine handling 50k RPM.",
    expected_salary: "₹38,00,000 / year",
    status: "shortlisted",
    created_at: new Date(Date.now() - 43200000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "app-102",
    job_id: "job-001",
    full_name: "Priya Nair",
    email: "priya.nair@frontend.dev",
    phone: "+91 98123 45678",
    portfolio_url: "https://priyanair.design",
    github_url: "https://github.com/priyanair",
    resume_url: "https://assets.auraminator.in/resumes/priya-nair-fullstack.pdf",
    cover_note: "Specialized in micro-spring Framer Motion interactions and strict TypeScript architecture for modern SaaS and Web3 marketplaces.",
    expected_salary: "₹32,00,000 / year",
    status: "under_review",
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

// ==========================================
// MOCK OFFERS & PROTECTED DEAL ROOMS
// ==========================================
export const MOCK_OFFERS: import("./types").Offer[] = [
  {
    id: "offer-001",
    product_id: "prod-009",
    buyer_id: "buyer-001",
    seller_id: "seller-004",
    initial_offer_amount: 380000,
    current_offer_amount: 410000,
    last_offered_by: "seller",
    status: "countered",
    terms_note: "Offer includes immediate escrow deposit upon acceptance. Requesting 30 days developer transition support.",
    created_at: new Date(Date.now() - 172800000).toISOString(),
    updated_at: new Date(Date.now() - 14400000).toISOString(),
    product: MOCK_PRODUCTS.find((p) => p.id === "prod-009"),
    buyer: {
      id: "buyer-001",
      full_name: "Alex Mercer",
      username: "alexmercer",
      avatar_url: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80",
      role: "buyer",
      is_verified: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    seller: MOCK_PRODUCTS.find((p) => p.id === "prod-009")?.seller,
  },
  {
    id: "offer-002",
    product_id: "prod-012",
    buyer_id: "buyer-001",
    seller_id: "seller-001",
    initial_offer_amount: 350000,
    current_offer_amount: 365000,
    last_offered_by: "buyer",
    status: "accepted",
    terms_note: "Agreed to 7-day Google brand account transfer protocol. Ready for escrow lock.",
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: new Date(Date.now() - 3600000).toISOString(),
    product: MOCK_PRODUCTS.find((p) => p.id === "prod-012"),
    buyer: {
      id: "buyer-001",
      full_name: "Alex Mercer",
      username: "alexmercer",
      avatar_url: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80",
      role: "buyer",
      is_verified: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    seller: MOCK_PRODUCTS.find((p) => p.id === "prod-012")?.seller,
  }
];

export const MOCK_DEAL_ROOMS: import("./types").DealRoom[] = [
  {
    id: "deal-001",
    offer_id: "offer-001",
    product_id: "prod-009",
    buyer_id: "buyer-001",
    seller_id: "seller-004",
    agreed_price: 410000,
    platform_fee: 61500, // 15% platform commission
    seller_payout: 348500, // 85% seller net payout
    escrow_status: "buyer_inspecting",
    razorpay_order_id: "order_deal_9981249",
    razorpay_payment_id: "pay_escrow_8819203",
    deposit_timestamp: new Date(Date.now() - 43200000).toISOString(),
    inspection_period_hours: 48,
    inspection_deadline: new Date(Date.now() + 129600000).toISOString(),
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    product: MOCK_PRODUCTS.find((p) => p.id === "prod-009"),
    buyer: {
      id: "buyer-001",
      full_name: "Alex Mercer",
      username: "alexmercer",
      avatar_url: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80",
      role: "buyer",
      is_verified: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    seller: MOCK_PRODUCTS.find((p) => p.id === "prod-009")?.seller,
    transfers: [
      {
        id: "trf-001",
        deal_id: "deal-001",
        transfer_type: "domain_auth_code",
        credential_payload: "EPP-AUTH-CODE: #vividai-epp-99214981-sec",
        handover_instructions: "Use this EPP code at Namecheap/GoDaddy/Cloudflare Registrar to initiate the domain transfer.",
        verified_by_buyer: true,
        verified_at: new Date(Date.now() - 36000000).toISOString(),
        created_at: new Date(Date.now() - 40000000).toISOString(),
      },
      {
        id: "trf-002",
        deal_id: "deal-001",
        transfer_type: "github_repo_transfer",
        credential_payload: "GITHUB-INVITE: https://github.com/vividai-tools (Admin Role Granted to @alexmercer)",
        handover_instructions: "Accept the organization owner invitation on GitHub. Full repository IP rights transferred.",
        verified_by_buyer: true,
        verified_at: new Date(Date.now() - 28800000).toISOString(),
        created_at: new Date(Date.now() - 32000000).toISOString(),
      },
      {
        id: "trf-003",
        deal_id: "deal-001",
        transfer_type: "cloud_hosting_access",
        credential_payload: "STRIPE-TRANSFER-ID: acct_1N9xZ8K9L9s821 • Stripe customer recurring subscription billing ownership transferred.",
        handover_instructions: "Stripe team invite dispatched to alex@auraminator.in. Payout destination re-linked.",
        verified_by_buyer: false,
        created_at: new Date(Date.now() - 20000000).toISOString(),
      }
    ],
    messages: [
      {
        id: "msg-001",
        deal_id: "deal-001",
        sender_id: "buyer-001",
        sender_role: "buyer",
        message: "Submitted initial offer of ₹3,80,000 for VividAI Turnkey SaaS.",
        message_type: "counter_offer",
        created_at: new Date(Date.now() - 86400000).toISOString(),
      },
      {
        id: "msg-002",
        deal_id: "deal-001",
        sender_id: "seller-004",
        sender_role: "seller",
        message: "Countered at ₹4,10,000 including 30 days developer support and active Stripe accounts.",
        message_type: "counter_offer",
        created_at: new Date(Date.now() - 50000000).toISOString(),
      },
      {
        id: "msg-003",
        deal_id: "deal-001",
        sender_id: "buyer-001",
        sender_role: "buyer",
        message: "Offer of ₹4,10,000 accepted. Deposited ₹4,10,000 + Gateway fee into Auraminator Escrow.",
        message_type: "payment_deposit",
        created_at: new Date(Date.now() - 43200000).toISOString(),
      },
      {
        id: "msg-004",
        deal_id: "deal-001",
        sender_id: "seller-004",
        sender_role: "seller",
        message: "Submitted Domain EPP Code, GitHub Organization Invite, and Stripe Account handover credentials in the secure handover vault.",
        message_type: "credentials_submitted",
        created_at: new Date(Date.now() - 20000000).toISOString(),
      }
    ]
  }
];


